name: main

on:
  pull_request:
  push:
    branches: [main]

jobs:
  main:
    uses: mxr/workflows/.github/workflows/tox.yml@5eb392892650c7c675f5abc967bd39f31b77a5d8
    with:
      env: '["py312", "py313", "py314", "pypy7.3.13"]' # https://github.com/actions/runner-images/blob/50ae10289a1d019551858f6a174f78d2e212bed4/images/ubuntu/Ubuntu2204-Readme.md#pypy
  main-win:
    uses: mxr/workflows/.github/workflows/tox.yml@5eb392892650c7c675f5abc967bd39f31b77a5d8
    with:
      env: '["py312"]'
      os: windows-latest
