name: main

on:
  pull_request:
  push:
    branches: [main]

jobs:
  main:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.7.0
    with:
      env: '["py312", "py313", "py314", "pypy3"]'
  main-win:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.7.0
    with:
      env: '["py312"]'
      os: windows-latest
