name: release

on:
  push:
    tags:
    - '**'

permissions: {}

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    uses: mxr/workflows/.github/workflows/pypi-release.yml@f0281d9a23f65774fe530a52f03d5419ed871519           # v0.1.0
