name: release

on:
  push:
    tags:
    - '**'

permissions: {}

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: mxr/workflows/.github/workflows/pypi-release.yml@96a47675aa2e18981384cd018c2583accd9f797e
